### ISSUE TITLE
Default image error, even without token mold

### ISSUE THREAD

**Issue by jacksands** [javieros105/FVTT-TokenHUDWildcard#24] opened 2021-09-30 20:26 UTC
video -    https://www.dropbox.com/s/03ov78dwesmo6l1/2021-09-30%2017-16-55.mp4?dl=0

I was aware of the token mold issue, with the new update It seems resolved, but now its stranger, some times the default images apply correctly, but in others the token shows another image, but the hud show as it was the default...
then, all the sudden, it normalizes, I see the double tk issue, and what image is last selected does not seems to change the behavior for long...
sorry to bring bad news.. your module is nearly essential to my game! I remove the token mold completely. but the bug persists.

Anyway thank you for your effort!

Erich

**Comment by Dick-K** [comment] 2021-10-01 23:29
I've just noticed this as well, have never used token mold.

ETA: Tested with all other modules OFF, problem persists.

**Comment by javieros105** [comment] 2021-10-04 22:13
Thanks for the video, honeslty it's super weird, because I've been trying to replicate the problem and I can't

**Comment by jacksands** [comment] 2021-10-04 22:26
Question to those with the problem, are you using Sandbox System like myself?
I'm in contact with the dev and it may be and incompatibility with the sys...
the default token opinion for instance, resets when the actor needs a reload (common on sandbox), if tk wildcard is on, and the dev says it is a sandbox issue, not the module... 
but the token image error he does not knows anything about.. 

that may be the problem, the system

**Comment by Dick-K** [comment] 2021-10-04 22:36
I'm using Call of Cthulhu 7E (Unofficial).

**Comment by javieros105** [comment] 2021-12-01 00:17
I'm back at looking at this stuff, sorry for all the time it took. Is this still happening to any of you guys?

**Comment by Dick-K** [comment] 2021-12-01 00:38
I reverted to 1.4.0 where it works fine. I've locked updates for this module in Foundry.

**Comment by javieros105** [comment] 2021-12-01 01:27
I just did a test on Call of Cthulhu 7e and the only issue am seeing is that if default is not set and the random one has settings for some height width or scale it is not applied, but can't see the other issues :c.

Edited: This specific issue apparently it's not only for this system, it probably has to do with the hook I'm using in this version

**Comment by Dick-K** [comment] 2021-12-01 16:49
Thanks. I can confirm that, with no other modules running except Token HUD Wildcard, on Cthulhu 7E I get the double token error about every 3rd drop of the token. I tried this in an absolutely empty RuneQuest world and 1.5.0 works fine. So, perhaps some interaction with CoC7E? But GMs using other systems are also seeing this. Perhaps a populated world exposes a race condition? Don't know.
1.4.0 works fine, so I'm currently locked on that.

**Comment by javieros105** [comment] 2021-12-04 20:22
@Dick-K good to know that at least 1.4.0 is working properly as contingency, I'm trying to find the issue here. It's been a bit hard cause it works properly for me in the sense that i don't get the double token error at all neither in a modded world and in a non modded one so it's hard to replicate.

**Comment by cs96and** [comment] 2022-01-30 10:18
I posted a fix for this in issue #27...

https://github.com/javieros105/FVTT-TokenHUDWildcard/issues/27#issuecomment-1020067543

**Comment by javieros105** [comment] 2022-02-07 21:02
With @cs96and fix it's now properly working

**Closed as completed** 2022-02-07 21:02 UTC
Labels: bug, compatibility

**Comment by Dick-K** [comment] 2022-02-07 22:23
Thanks Javier, I installed 1.6 manually (the Foundry updater is still picking up 1.5) and it's working fine now and has reinstated the default image selector. Thanks also to @cs96and

**Comment by javieros105** [comment] 2022-02-08 21:02
Sadly Idk what's going there i had to uninstall mine and install from foundry worked properly but updating wasn't

**Comment by cs96and** [comment] 2022-02-08 22:06
The manifest link in your module.json is pointing to a specific version.  It should point to "latest"

**Comment by javieros105** [comment] 2022-02-08 23:04
> The manifest link in your module.json is pointing to a specific version. It should point to "latest"

Weird, I changed the module.json on the release and it still not updating

Ignore me, fixed it

**Comment by cs96and** [comment] 2022-02-09 10:55
When I tried to update from 1.5.0 to 1.6.0 I got this...

![image](https://user-images.githubusercontent.com/898086/153184164-ec2e627d-0efc-42f7-9bef-c4816e7274a0.png)

**Comment by cs96and** [comment] 2022-02-09 10:56
Trying to navigate to that URL manually, I get "404: not found."
https://raw.githubusercontent.com/javieros105/FVTT-TokenHUDWildcard/master/token-hud-wildcard/module.json

**Comment by javieros105** [comment] 2022-02-09 14:20
yeah, sorry about that I made some changes to the repo and that broke it, I can re add that file. So it updates properly, going forward the file links should be taken from master but from the releases so there won't be more problems

**Comment by javieros105** [comment] 2022-02-09 14:21
Done, should be able to update properly now I think
